### ISSUE TITLE
noise in baseline raw filter curves

### ISSUE THREAD

**Issue by johannct** [lsst/throughputs#8]
I plotted the raw filters (filter_*.dat for ugrizy) in linear and semilogy space (see attached figures). I presume that the rise of some filter at the extreme right is physical, but in semilogy the noise in the derived curves is apparent, and not completely negligible apriori. It shows up in the https://github.com/DarkEnergyScienceCollaboration/PhotoZDC1 work, where it needs to be thresholded out in order to avoid extra CPU time in quad integrations. The thersholding can be a little bit more complicated there, because atmosphere and optics effects make some thresholds much smoother... So I meant to ask here whether this noise level in the throughputs file is absolutely necessary to keep, or if it might be the place where some trimming should occur, prior to any further computation with the raw filter curves.
![filters_only_log](https://cloud.githubusercontent.com/assets/586081/12508786/3f5baf00-c0fe-11e5-8a7f-4ccadb3f4c75.png)
![filters_only_lin](https://cloud.githubusercontent.com/assets/586081/12508787/3f5c1422-c0fe-11e5-9796-13c6572f5216.png)

**Comment by rhiannonlynne** [comment]
The filter curves in the current collection are based on a simulation of what an actual physical filter throughput curve might look like - it's a simulation attempting to predict the throughput based on multiple layers deposited onto an appropriate substrate. That's why there is the red leak in some bandpasses (that rise in the redmost wavelengths) and why there is some noise in the wavelengths between that red leak and the actual throughput region. 

We are about to update the throughput curves for all components, in particular the detector and mirror curves will obviously change. One of the updates is also in the filter curves -- instead of these simulated curves of physical throughputs, the new filter curves will represent the requirements for the vendors. These 'vendor requirement' curves are simple trapezoids defining the desired wavelength regions for each bandpass, and will not have either the red leak or the out-of-band noise you describe above. 

So -- the noise will go away very shortly, if that's helpful. 
(note: if you want to examine these "to-be-official" curves now, you can check out the "Update-from-syseng_" branch of this repository. it would be useful to know if you have any comments).

**Comment by johannct** [comment]
thanks @rhiannonlynne Here is what I get when comparing master and branch total curves (dash:master, full:syseng).
![comparison](https://cloud.githubusercontent.com/assets/586081/12533024/54f8fd24-c223-11e5-9f73-ddd8160f28b0.png)
Indeed noise and leaks have disappeared, and below ~1.e-1 1.e-2 the bandpasses are not widening. The syseng u filter has a lower relative transmission than the master version.

**Comment by johannct** [comment]
there are negative values in some total_*.dat filters : 
total_u.dat : l.1091
total_r.dat : l.4065
total_z.dat : l.6391

**Comment by rhiannonlynne** [comment]
These very small negative numbers are likely the result of interpolation. Thanks for noticing, I'll get those removed.
